#!/system/bin/sh

command=$1
namespace=$2
key=$3
value=$4
file="$MOCK_STORE/${namespace}_${key}"

case "$command" in
  get)
    if [ -f "$file" ]; then
      cat "$file"
    else
      echo null
    fi
    ;;
  put)
    printf '%s\n' "$value" > "$file"
    ;;
  delete)
    rm -f "$file"
    ;;
  *)
    exit 2
    ;;
esac

